apiVersion: v1
kind: Service
metadata:
  name: pioneers-dev-compute-node-service
  namespace: default
spec:
  ports:
  - port: 6420
    protocol: TCP
    targetPort: 6420
  selector:
    run: pioneers-dev-compute-node
  type: NodePort